### ISSUE TITLE
Production build error

### ISSUE THREAD

**Issue by chhaunkar96** [seanpmaxwell/express-generator-typescript#24]
I'm trying to run production after the build. But It's not working.

```
kaushal@kaushal-pc:~/Documents/project$ npm start

> RLC@1.0.0 start /home/kaushal/Documents/project/
> node -r module-alias/register ./dist

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '/home/kaushal/Documents/project/dist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._resolveFilename (/home/kaushal/Documents/project/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! RLC@1.0.0 start: `node -r module-alias/register ./dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the RLC@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kaushal/.npm/_logs/2020-04-27T17_00_37_944Z-debug.log

```
can you help me to solve this problem?

**Comment by seanpmaxwell** [comment]
Did you use `npm run build` and then right afterwords do `npm start` in the same directory? I just tried that and it worked for me.

**Comment by chhaunkar96** [comment]
yes
`npm run build`
output:
```
> RLC@1.0.0 build /home/kaushal/Documents/project
> node ./util/build.js
```


![image](https://user-images.githubusercontent.com/29665934/80401565-29937880-88da-11ea-9ba0-8e19e8f2486f.png)

**Comment by seanpmaxwell** [comment]
Did you modify the tsconfig file? dist is not supposed to contained util or views. dist/ is supposed to have all the same folders as src/.

**Comment by chhaunkar96** [comment]
No.
**tsconfig.json**
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "module": "commonjs",
    "outDir": "dist",
    "removeComments": true,
    "sourceMap": true,
    "strict": true,
    "target": "es6",
    "moduleResolution": "node",
    "paths": {
      "@daos/*": [
        "src/daos/*"
      ],
      "@entities/*": [
        "src/entities/*"
      ],
      "@shared/*": [
        "src/shared/*"
      ],
      "@server": [
        "src/Server"
      ],
      "@models/*": [
        "src/models/*"
      ],
      "@config/*": [
        "src/config/*"
      ]
    },
    "types": [
      "node"
    ],
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "include": [
    "src/**/*.ts",
    "spec/**/*.ts"
  ],
  "exclude": [
    "src/public/"
  ]
}
```
**tsconfig.prod.json**
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "sourceMap": false
  },
  "exclude": [
    "spec",
    "src/**/*.mock.ts",
    "src/public/"
  ]
}
```

**Comment by chhaunkar96** [comment]
My mistake I created a ts file into utils directory.
