### ISSUE TITLE
Project setup error

### ISSUE THREAD

**Issue by temetvince** [seanpmaxwell/express-generator-typescript#29]
First of all, thanks for your work.

Running `npx express-generator-typescript` on my Windows 10 fails with an Unexpected end of JSON input error. Node 12.18.0 LTS.

```
$ npx express-generator-typescript
Setting up new Express/TypeScript project...
npm ERR! Unexpected end of JSON input while parsing near '...registry.npmjs.org/ts'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\temet\AppData\Roaming\npm-cache\_logs\2020-06-03T20_52_22_094Z-debug.log
Error: Command failed: npm i -D ts-node tslint typescript nodemon find jasmine supertest @types/node @types/express @types/jasmine @types/find @types/morgan @types/cookie-parser @types/supertest fs-extra tsconfig-paths @types/jsonfile jsonfile @types/command-line-args @types/helmet
npm ERR! Unexpected end of JSON input while parsing near '...registry.npmjs.org/ts'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\temet\AppData\Roaming\npm-cache\_logs\2020-06-03T20_52_22_094Z-debug.log

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at downloadNodeModules (C:\ProgramData\nvm\v12.17.0\node_modules\express-generator-typescript\lib\express-generator-typescript.js:67:18)
    at expressGenTs (C:\ProgramData\nvm\v12.17.0\node_modules\express-generator-typescript\lib\express-generator-typescript.js:18:9) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 6e 70 6d 20 45 52 52 21 20 55 6e 65 78 70 65 63 74 65 64 20 65 6e 64 20 6f 66 20 4a 53 4f 4e 20 69 6e 70 75 74 20 77 68 69 6c 65 20 70 61 72 73 69 6e ... 183 more bytes>
  ],
  pid: 2044,
  stdout: <Buffer >,
  stderr: <Buffer 6e 70 6d 20 45 52 52 21 20 55 6e 65 78 70 65 63 74 65 64 20 65 6e 64 20 6f 66 20 4a 53 4f 4e 20 69 6e 70 75 74 20 77 68 69 6c 65 20 70 61 72 73 69 6e ... 183 more bytes>
}
Project setup complete!

```

**Comment by seanpmaxwell** [comment]
Hmm I just ran it on windows 10 and it worked fine for me hmmmm try running:
npm i -D ts-node tslint typescript nodemon find jasmine supertest ' +
        '@types/node @types/express @types/jasmine @types/find @types/morgan ' +
        '@types/cookie-parser @types/supertest fs-extra tsconfig-paths @types/jsonfile ' +
        'jsonfile @types/command-line-args @types/helmet

directly cause it looks like that command is failing in the script

**Comment by temetvince** [comment]
Hi Sean. I tried as you recommended and then searched the error messages online. After investigating a little I believe my Windows node install is borked. My apologies and thank you for your help!
