### ISSUE TITLE
npm run start:dev got errors of jet-logger

### ISSUE THREAD

**Issue by HiroyoshiMori** [seanpmaxwell/express-generator-typescript#58]
I got the following error after "npx express-generator-typescript app_name" and "npm run start:dev".

```
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/shared/Logger.ts:10:5 - error TS2304: Cannot find name 'thirdPartyLoggingApp'.

10     thirdPartyLoggingApp.doStuff(...);
       ~~~~~~~~~~~~~~~~~~~~
src/shared/Logger.ts:10:37 - error TS1109: Expression expected.

10     thirdPartyLoggingApp.doStuff(...);
                                       ~

    at createTSError (D:\Repos\ScriptLab\react\express_type_app\node_modules\ts-node\src\index.ts:750:12)
    at reportTSError (D:\Repos\ScriptLab\react\express_type_app\node_modules\ts-node\src\index.ts:754:19)
    at getOutput (D:\Repos\ScriptLab\react\express_type_app\node_modules\ts-node\src\index.ts:941:36)
    at Object.compile (D:\Repos\ScriptLab\react\express_type_app\node_modules\ts-node\src\index.ts:1243:30)
    at Module.m._compile (D:\Repos\ScriptLab\react\express_type_app\node_modules\ts-node\src\index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Repos\ScriptLab\react\express_type_app\node_modules\ts-node\src\index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticText: "\x1B[96msrc/shared/Logger.ts\x1B[0m:\x1B[93m10\x1B[0m:\x1B[93m5\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2304: \x1B[0mCannot find name 'thirdPartyLoggingApp'.\r\n" +
    '\r\n' +
    '\x1B[7m10\x1B[0m     thirdPartyLoggingApp.doStuff(...);\r\n' +
    '\x1B[7m  \x1B[0m \x1B[91m    ~~~~~~~~~~~~~~~~~~~~\x1B[0m\r\n' +
    '\x1B[96msrc/shared/Logger.ts\x1B[0m:\x1B[93m10\x1B[0m:\x1B[93m37\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS1109: \x1B[0mExpression expected.\r\n' +
    '\r\n' +
    '\x1B[7m10\x1B[0m     thirdPartyLoggingApp.doStuff(...);\r\n' +
    '\x1B[7m  \x1B[0m \x1B[91m                                    ~\x1B[0m\r\n',
  diagnosticCodes: [ 2304, 1109 ]
}
[nodemon] app crashed - waiting for file changes before starting...

```

To fix, I changed src/shared/Logger.ts to the followings, but I assume this is temporary fix.

```
import logger from 'jet-logger';

export default logger;

```

**Comment by seanpmaxwell** [comment]
fixed
