### ISSUE TITLE
 Property 'id' does not exist on type 'string[]'.

### ISSUE THREAD

**Issue by MiKr13** [seanpmaxwell/express-generator-typescript#6]
On first time setup I got an error:

```
TSError: ⨯ Unable to compile TypeScript:
src/routes/Users.ts:77:35 - error TS2339: Property 'id' does not exist on type 'Params'.
  Property 'id' does not exist on type 'string[]'.

77     return console.log(req.params.id);
                                     ~~

    at createTSError (E:\TypeScript\boilerplate\node_modules\ts-node\src\index.ts:245:12)
    at reportTSError (E:\TypeScript\boilerplate\node_modules\ts-node\src\index.ts:249:19)
    at getOutput (E:\TypeScript\boilerplate\node_modules\ts-node\src\index.ts:362:34)
    at Object.compile (E:\TypeScript\boilerplate\node_modules\ts-node\src\index.ts:395:32)
    at Module.m._compile (E:\TypeScript\boilerplate\node_modules\ts-node\src\index.ts:473:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.require.extensions.(anonymous function) [as .ts] (E:\TypeScript\boilerplate\node_modules\ts-node\src\index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
This was solved after changing:
`router.delete('/delete/:id', async (req: Request, res: Response) => {`
to
`router.delete('/delete/:id', async (req: any, res: Response) => {`
But this approach doesn't feels correct.

---------------------------------------------------------
This is how I solved it for now:

```
router.delete('/delete/:id', async (req: Request, res: Response) => {
    try {
        const idJSON = req.params;
        const id = idJSON;
        await userDao.delete(Number(id));
        return res.status(OK).end();
    } catch (err) {
        logger.error(err.message, err);
        return res.status(BAD_REQUEST).json({
            error: err.message,
        });
    }
});
```

**Comment by seanpmaxwell** [comment]
Thanks for finding this. Weird that it just start happening, haven't had this issue before. I think it has to do with a TypeScript updated. I noticed that there is this line express typings. 
`export type Params = ParamsDictionary | ParamsArray;`
The issue is that if you use a regular expression for the path, (mine does not) params will be an array instead of an object. This of course creates a typing issue cause an array will not have the 'id' property.

I wasn't sure what the best solution was so I just casted the params property to ParamsDictionary. Extending the express.Request object didn't work.

const { id } = req.params as ParamsDictionary;
