### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by canbax** [seanpmaxwell/express-generator-typescript#73]
node 18 on Mac OS 13

[nodemon] starting `./node_modules/.bin/ts-node --files -r tsconfig-paths/register ./src`
Error: dlopen(/Users/yusufcanbaz/Desktop/yusuf/namaz-vakti-api-2/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node, 0x0001): tried: '/Users/yusufcanbaz/Desktop/yusuf/namaz-vakti-api-2/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/yusufcanbaz/Desktop/yusuf/namaz-vakti-api-2/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node' (no such file), '/Users/yusufcanbaz/Desktop/yusuf/namaz-vakti-api-2/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/yusufcanbaz/Desktop/yusuf/namaz-vakti-api-2/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .js] (/Users/yusufcanbaz/Desktop/yusuf/namaz-vakti-api-2/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by seanpmaxwell** [comment]
hmm, looks like an issue with bcrypt, I just ran this on mac os with node 16.18.0 and it worked fine. maybe bcypt has an issue with the latest node?

**Comment by JohannesMogashoa** [comment]
It is working fine for me. I just tried it now with node 19 on Windows with no errors.
