### ISSUE TITLE
I can't deploy my app on Azure 

### ISSUE THREAD

**Issue by elkin0727** [seanpmaxwell/express-generator-typescript#8]
Hi.

I have a problem with deploying the app in Azure.

The command: **npm run start** generates the next error:

```
2019-09-17T17:32:15.075119582Z > myexpressapp@0.0.0 start /home/site/wwwroot
2019-09-17T17:32:15.075135283Z > cross-env ENV_FILE=production node -r ./env -r module-alias/register ./dist/start.js
2019-09-17T17:32:15.075140583Z 
2019-09-17T17:32:15.611200168Z internal/modules/cjs/loader.js:583
2019-09-17T17:32:15.611228570Z     throw err;
2019-09-17T17:32:15.611233470Z     ^
2019-09-17T17:32:15.611237070Z 
2019-09-17T17:32:15.611240770Z Error: Cannot find module '..'
2019-09-17T17:32:15.611244570Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2019-09-17T17:32:15.611248670Z     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2019-09-17T17:32:15.611253171Z     at Module.require (internal/modules/cjs/loader.js:637:17)
2019-09-17T17:32:15.611257071Z     at require (internal/modules/cjs/helpers.js:22:18)
2019-09-17T17:32:15.611260671Z     at Object. (/home/site/wwwroot/node_modules/.bin/cross-env:4:16)
2019-09-17T17:32:15.611264971Z     at Module._compile (internal/modules/cjs/loader.js:689:30)
2019-09-17T17:32:15.611268571Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2019-09-17T17:32:15.611272271Z     at Module.load (internal/modules/cjs/loader.js:599:32)
2019-09-17T17:32:15.611275871Z     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2019-09-17T17:32:15.611279672Z     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
2019-09-17T17:32:15.671881457Z npm ERR! code ELIFECYCLE
2019-09-17T17:32:15.700250121Z npm ERR! errno 1
2019-09-17T17:32:15.708948777Z npm ERR! myexpressapp@0.0.0 start: `cross-env ENV_FILE=production node -r ./env -r module-alias/register ./dist/start.js`
2019-09-17T17:32:15.709719209Z npm ERR! Exit status 1
2019-09-17T17:32:15.710555543Z npm ERR! 
2019-09-17T17:32:15.711515983Z npm ERR! Failed at the myexpressapp@0.0.0 start script.
2019-09-17T17:32:15.718314961Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-09-17T17:32:15.816054370Z 
2019-09-17T17:32:15.817110013Z npm ERR! A complete log of this run can be found in:
2019-09-17T17:32:15.817851744Z npm ERR!     /root/.npm/_logs/2019-09-17T17_32_15_719Z-debug.log
```

So... I need your help, please!

**Comment by seanpmaxwell** [comment]
did you remember to build it first with `npm run build` this generates the .js files that are used for production

**Comment by elkin0727** [comment]
Hi. I tried to build the app... however, It doesn't work... Show the same message. In my local environment works, but azure nop :( 
I need ideas please... I'm working on it for more than 5 hours.

**Comment by seanpmaxwell** [comment]
Have you installed all the npm modules on your remote env. with 'npm I'm.

**Comment by seanpmaxwell** [comment]
That error message looks like you are missing a .js file. Either a npm module or one that is part of your project

**Comment by sandorTuranszky** [comment]
The original express-generator uses `normalizePort` to check if port is a string or a number. I can't see this function being used in express-generator-typescript project. Azure uses pipes which are strings. Can this be related? 

```
/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

var port = normalizePort(process.env.PORT || '3000');
...

```

**Comment by seanpmaxwell** [comment]
express-generator-typescript uses Number(process.env.PORT || 3000). So I don't think that's the issue. It's missing a library or a .js file. Try this, transpile your app locally. Deploy it. Go into the remote env and in the project folder run npm i.

**Comment by elkin0727** [comment]
Finally, I found the problem. The module cross-env was generating the error.

I found the solution on [stackoverflow](https://stackoverflow.com/questions/49149361/cross-env-cant-find-module):

In summary, we have to call the internal command cross-env:

`"start": "node node_modules/cross-env/dist/bin/cross-env.js ENV_FILE=production node -r ./env -r module-alias/register ./dist/start.js",`

Thank you ;)
