### ISSUE TITLE
npm test gives error 

### ISSUE THREAD

**Issue by libudas** [seanpmaxwell/express-generator-typescript#88]
when trying to run npm test give me error 
```
npm test 

> express-gen-ts@0.0.0 test
> nodemon --config ./spec/nodemon.json

[nodemon] 3.1.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): spec/**/*
[nodemon] watching extensions: spec.ts
[nodemon] starting `./node_modules/.bin/ts-node --files -r tsconfig-paths/register ./spec`
/test-06/express-gen-ts/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
spec/tests/users.spec.ts:47:5 - error TS2322: Type 'TestAgent<Test>' is not assignable to type 'SuperTest<Test>'.
  Type 'TestAgent<Test>' is not assignable to type 'RequestMethods<Test>'.
    Types of property 'ACL' are incompatible.
      Type '(url: string) => Test' is not assignable to type 'HttpMethod<Test>'.
        Type '(url: string) => Test' is not assignable to type '(url: URLType, callback?: CBHandler | undefined) => Test'.
          Types of parameters 'url' and 'url' are incompatible.
            Type 'URLType' is not assignable to type 'string'.
              Type 'URL' is not assignable to type 'string'.

47     agent = supertest.agent(app);
       ~~~~~

    at createTSError (/test-06/express-gen-ts/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/test-06/express-gen-ts/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/test-06/express-gen-ts/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/test-06/express-gen-ts/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/test-06/express-gen-ts/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Object.require.extensions.<computed> [as .ts] (/test-06/express-gen-ts/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19) {
  diagnosticCodes: [ 2322 ]
}
[nodemon] app crashed - waiting for file changes before starting...

```
Please can someone help

**Comment by seanpmaxwell** [comment]
thx for reporting this, error was due to an update in supertest, fixed!
