### ISSUE TITLE
Production build not working in dockerized container

### ISSUE THREAD

**Issue by amanpreet-dev** [seanpmaxwell/express-generator-typescript#92]
Hi,

I have been trying to dockerize this app but somehow whenever I try to build a production build it gives me error. 

```
2024-05-14 18:14:16 
2024-05-14 18:14:16 > express-gen-ts@0.0.0 prestart
2024-05-14 18:14:16 > npm run build
2024-05-14 18:14:16 
2024-05-14 18:14:16 
2024-05-14 18:14:16 > express-gen-ts@0.0.0 build
2024-05-14 18:14:16 > npx ts-node build.ts
2024-05-14 18:14:16 
2024-05-14 18:14:17 npm WARN exec The following package was not found and will be installed: ts-node@10.9.2
2024-05-14 18:14:22 /root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859
2024-05-14 18:14:22     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
2024-05-14 18:14:22            ^
2024-05-14 18:14:22 TSError: ⨯ Unable to compile TypeScript:
2024-05-14 18:14:22 build.ts(7,16): error TS2307: Cannot find module 'fs-extra' or its corresponding type declarations.
2024-05-14 18:14:22 build.ts(36,28): error TS7006: Parameter 'err' implicitly has an 'any' type.
2024-05-14 18:14:22 build.ts(47,32): error TS7006: Parameter 'err' implicitly has an 'any' type.
2024-05-14 18:14:22 
2024-05-14 18:14:22     at createTSError (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859:12)
2024-05-14 18:14:22     at reportTSError (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:863:19)
2024-05-14 18:14:22     at getOutput (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1077:36)
2024-05-14 18:14:22     at Object.compile (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1433:41)
2024-05-14 18:14:22     at Module.m._compile (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1617:30)
2024-05-14 18:14:22     at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
2024-05-14 18:14:22     at Object.require.extensions.<computed> [as .ts] (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1621:12)
2024-05-14 18:14:22     at Module.load (node:internal/modules/cjs/loader:1113:32)
2024-05-14 18:14:22     at Function.Module._load (node:internal/modules/cjs/loader:960:12)
2024-05-14 18:14:22     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
2024-05-14 18:14:22   diagnosticCodes: [ 2307, 7006, 7006 ]
2024-05-14 18:14:22 }
```

My Dockerfile is as follows - 
```
FROM node:20.2.0-slim
WORKDIR /app
COPY package.json .

ARG NODE_ENV
RUN npm install
# RUN if [ "$NODE_ENV" = "production" ]; \
#     then npm install --only=production; \
#     else npm install; \
#     fi

COPY . .
EXPOSE ${PORT}
```

and the compose file is as follows - 
```
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    env_file: env/production.env
    ports:
      - 8081:8081
    command: npm run start
```

Interestingly it works perfectly fine in development environment, but somehow for production build it fails.

**Comment by amanpreet-dev** [comment]
Also I have added a prestart script in `package.json` file 

```
"prestart": "npm run build",
```

**Comment by seanpmaxwell** [comment]
So your error shows that `fs-extra` is missing. You ran install with the `production` only flag. In package.json fs-extra is a dev dependency. In order to run the build script you need to install dev dependencies as well. Production only install should only be done in a remote environment after the build is finished.

**Comment by seanpmaxwell** [comment]
Still the fs-extra error? or just the `Parameter 'err' implicitly has an 'any' type.` now?

**Comment by amanpreet-dev** [comment]
Actually it is somehow working now, I did changed my `Dockerfile` to have a multi stage build and instead of running command from compose file I added it in the `Dockerfile`

here is my `Dockerfile` content
```
# Build Stage
FROM node:20.2.0-slim as build

WORKDIR /app

ARG ENV_FILE=development.env

COPY ./env/${ENV_FILE} .env

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

# Production Stage
FROM node:20.2.0-slim as production

WORKDIR /app

ARG ENV_FILE=production.env

COPY ./env/${ENV_FILE} .env

COPY package*.json .

RUN npm ci --only=production

COPY --from=build /app/dist ./dist

CMD ["node", "-r", "module-alias/register", "./dist", "--env=production"]

```

The last line made the difference,before closing this issue I will keep analysing it and in case of any issue will add as comments.

**Comment by seanpmaxwell** [comment]
I'ma close this issue now. I hope it ends up being useful for others in the future using docker.

**Comment by ganker-vito** [comment]
my build action is not in docker pod .  How can i build fully depencicies project for production ?
